### ISSUE TITLE
[Idea] Reset stats :)?

### ISSUE THREAD

**Issue by Robpizza** [BtoBastian/bStats-Metrics#13]
Hello,

I was wondering if you could add an option to reset the stats because I removed my config a couple times when I was testing my plugin and now I have the same server a couple times in my stats :P

Thank you in advance,

Regards,
Robpizza.

**Comment by BtoBastian** [comment]
Hey,
you can just delete the plugin and readd it to purge all stats. :)
An extra option to reset all stats isn't necessary in my opinion, because I don't think it would be used a lot.

**Comment by Robpizza** [comment]
Oh right xD
Thank you :P
