### ISSUE TITLE
NPE when checking for System.getProperty("bstats.relocatecheck")

### ISSUE THREAD

**Issue by timbru31** [BtoBastian/bStats-Metrics#14]
This line is causing an NPE:
https://github.com/BtoBastian/bStats-Metrics/blob/development/bstats-bukkit/src/main/java/org/bstats/Metrics.java#L40

Due to the fact that the `System.getProperty` returns `null` when the key does not exists. (see http://docs.oracle.com/javase/7/docs/api/java/lang/System.html#getProperty(java.lang.String))

An additional null check is needed.

**Comment by BtoBastian** [comment]
Great, thank you.
I didn't have time to test it yet. :)

**Comment by timbru31** [comment]
No worries. I can create a PR later if you want 👍
