### ISSUE TITLE
Using the BungeeCord Scheduler instead of Timers.

### ISSUE THREAD

**Issue by shawn-ian** [BtoBastian/bStats-Metrics#16]
Plugin [caused error](https://github.com/AuraDevelopmentTeam/BungeeChat2/issues/12) because of incorrect API usage, mostly caused by the usage of Timers ([line 168](https://github.com/BtoBastian/bStats-Metrics/blob/master/bstats-bungeecord/src/main/java/org/bstats/Metrics.java#L168)). As Timers are discouraged/outdated for a long time now, it would might be an idea to use the BungeeCord Scheduler system instead (as it is less likely te get such errors when using them).

**Comment by BtoBastian** [comment]
Hey,
thank you. I'll fix it asap :-)

**Comment by BtoBastian** [comment]
Fixed in version 1.2
