### ISSUE TITLE
How to confirm it works?

### ISSUE THREAD

**Issue by tastybento** [BtoBastian/bStats-Metrics#2]
I've integrated MetricsLite into ASkyBlock and AcidIsland, but I'm trying to confirm it works. I added some debug and it looks like the stats are sent to the server, but as of yet I don't see any report on my account for the plugin. I was hoping to see 1 Server listed. Should it show up immediately?

Hmm, the server response says:
{"error":"Connection throttled!"}

Maybe that's the problem. Will it reset at some point?

**Comment by randombyte-developer** [comment]
After half an hour it should show up. Make sure the server runs at least 5 minutes so the stats get send. 
And maybe the error originates from too many attempts from the same server to send data.

**Comment by BtoBastian** [comment]
https://bstats.org/plugin/bukkit/ASkyBlock
Looks like it works now? The site refreshes it's charts every 30 minutes (At xx:00 and xx:30).
If you send two requests in this interval (e.g. because of an server restart) the connection get throttled.

**Comment by tastybento** [comment]
Okay, I got it. Thanks!
