### ISSUE TITLE
Sort Problems after Sorting with Mobile Version

### ISSUE THREAD

**Issue by Luc1412** [BtoBastian/bStats-Metrics#22]
I sort the charts from my Plugin with my Phone in the Webbrowser. That was very buggy and didn't worke. After this it didn't worke on my Pc too.

Informations:
   Phone Browser: Samsung Internet Beta
   Pc Browser: Opera Dev
   Phone: Samsung Galaxy S7 edge
   PluginName: EasyMaintenance
   Version: Full Version(Not Lite) Bukkit Edition

**Comment by BtoBastian** [comment]
Should be fixed since ~3 month (duplicate of https://github.com/BtoBastian/bStats/issues/23)
