### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by rafedup27** [BtoBastian/bStats-Metrics#25]
I really want to delete all of the default charts and only use the ones i want.

**Comment by Derkades** [comment]
The website says "comming soon"

(side note: coming soon should be with one m)

**Comment by rafedup27** [comment]
coming soon is since its first release. when will coming soon be actually a coming soon?

**Comment by sgdc3** [comment]
The developer earns nothing from this project, he works on it in his free time, atm he is working on optimizing the backend, please be patient.

**Comment by BtoBastian** [comment]
@rafedup27
Default charts can't be deleted.
I don't see any benefits in hiding them (which might be possible) and not sending them at all is not possible as the data is also used for global charts and other bStats plugin on the same server.

@Derkades 
Thank you 👍

**Comment by rafedup27** [comment]
Ok. Thank you!

**Comment by rafedup27** [comment]
When will bstats get open?

**Comment by sgdc3** [comment]
@rafedup27 what do you mean?

**Comment by rafedup27** [comment]
Well, yesterday it was down for me saying "retry for a live version".

**Comment by Derkades** [comment]
@rafedup27 bStats as some problems at xx:00 and xx:30 when statistics are updated

**Comment by BtoBastian** [comment]
Well, this time it was really a crash. I'm sorry for the inconvenience. :/

**Comment by rafedup27** [comment]
No need for sorry! Can you please mark it as solved/closed?
