### ISSUE TITLE
Not all Plugins show the Plugin version. And I can not login to my account. Why?

### ISSUE THREAD

**Issue by montlikadani** [BtoBastian/bStats-Metrics#26]
It does not display the Plugin version on any of the plugins.
**And I can not login to my account.**
Recently, it did not show the Server location yet, but I did.

Images/Pictures:
![kep](https://user-images.githubusercontent.com/30026208/31616581-5aa4e4b6-b28d-11e7-8a21-0ec2cca5fa00.png)

**Comment by BtoBastian** [comment]
Hey,
are you sure you can't login to your account?
Login should be fixed since yesterday.

**Comment by montlikadani** [comment]
Yes, I'm sure I can not log in multiple times but not.

**Comment by BtoBastian** [comment]
What happens when you try to login?
And what's your account name?

**Comment by montlikadani** [comment]
Oh, I just entered my account now and it's good.

**Comment by BtoBastian** [comment]
Good. :)
The "Plugin Version" bug is also worked on and should be fixed, soon. 👍
