### ISSUE TITLE
Why can not I pull the charts?

### ISSUE THREAD

**Issue by montlikadani** [BtoBastian/bStats-Metrics#27]
So I tried to edit the charts but I did not know I did not get the page back in vain.

Images/Pictures:
![kep](https://user-images.githubusercontent.com/30026208/31827980-513f02ce-b5b9-11e7-98e3-cc6e1c0408c2.png)

**Comment by BtoBastian** [comment]
Reordering charts doesn't work at the moment. It will be reimplemented, soon.

**Comment by montlikadani** [comment]
All right. 👍

**Comment by montlikadani** [comment]
Now it is working. 👍
