### ISSUE TITLE
Mistakes/errors

### ISSUE THREAD

**Issue by montlikadani** [BtoBastian/bStats-Metrics#28]
Problems:
- My problem would be that when I add some charts I can not delete it afterwards because it will not let me.

- The next issue is to indicate offline mode when the server is running properly.

- The other problem is that when I encoded the charts and added I wait about. The page is refreshed for one and a half hours, and no number is shown in the charts. Here is the code I wrote very hard:

> 			Metrics metrics = new Metrics(this);
> 			Integer dela = getConfig().getInt("teleport-delay");
> 			metrics.addCustomChart(new Metrics.SimplePie("teleport_delay", new Callable<String>() {
> 				@Override
> 				public String call() throws Exception {
> 					return dela.toString();
> 					}
> 				}));
Here's an example of just running a server: https://bstats.org/plugin/bukkit/SetTheSpawn/#teleport_delay
https://bstats.org/plugin/bukkit/SetTheSpawn/#onlineMode

**Comment by BtoBastian** [comment]
Hey, thank you for the bug report.
1. Deleting and reordering charts doesn't not work at the moment because of the rewrite. These features should be available again, soon™.
2. Are you sure, the server is running in online mode? It cannot detect, if the server is behind a bungeecord proxy which requires your server to be in offline mode.
3. Your chart id is wrong. It's `teleport_delay` not `teleport-delay`

**Comment by montlikadani** [comment]
I do not use Bungeecord on a single base server.
The `teleport-delay` is in the configuration statement.

**Comment by BtoBastian** [comment]
I just did some testing and can confirm that the custom charts don't work.
However, I cannot reproduce the online mode bug. Can you pelase check, if the `Bukkit.getOnlineMode()` returns the correct online mode, because that's what the Metrics class is using.

**Comment by BtoBastian** [comment]
GJ Github...

**Comment by BtoBastian** [comment]
The custom chart problem should now be fixed for newly created custom charts.
I'll have to fix all other custom charts manually. If you have this problem with an other plugin, too, pls tell me.

**Comment by montlikadani** [comment]
Thanks! I'm sending a chart here: https://bstats.org/plugin/bukkit/AutoMessager/#using_placeholderapi
Code:
`	    Boolean randm = getConfig().getBoolean("random");
	    Integer dela = getConfig().getInt("time");
		    Metrics metrics = new Metrics(this);
	        metrics.addCustomChart(new Metrics.SimplePie("using_placeholderapi", new Callable<String>() {
	            @Override
	            public String call() throws Exception {
	                return papi.toString();
	            }
	            }));
	        metrics.addCustomChart(new Metrics.SimplePie("using_random_messages", new Callable<String>() {
	            @Override
	            public String call() throws Exception {
	                return randm.toString();
	            }
	            }));
	        metrics.addCustomChart(new Metrics.SimplePie("message_delay", new Callable<String>() {
				@Override
				public String call() throws Exception {
					return dela.toString();
				}
	        }));`

**Comment by montlikadani** [comment]
@BtoBastian 
Now it is working!
You just can not delete and edit it yet.

**Comment by BtoBastian** [comment]
Deleting charts should now also work. :)
