### ISSUE TITLE
Cannot delete custom charts

### ISSUE THREAD

**Issue by AlessioDP** [BtoBastian/bStats-Metrics#29]
I cannot delete these charts that I've created 2 weeks ago:
![Image](https://puu.sh/yiWhg/e02a0664d9.png)

They are bugged, don't count any data.

**Comment by montlikadani** [comment]
@AlessioDP 
Currently, the delete charts function does not work.

**Comment by AlessioDP** [comment]
Is there an ETA? :)

**Comment by montlikadani** [comment]
@AlessioDP 
Yes, even BETA.

**Comment by BtoBastian** [comment]
Hey,
what's the name of your plugin?
The bug is solved for newly created charts, but the charts which are already bugged must be fixed manually.
(See https://github.com/BtoBastian/bStats-Metrics/issues/28)

**Comment by AlessioDP** [comment]
The plugin is OreAnnouncer (https://bstats.org/plugin/bukkit/OreAnnouncer)
Last ones below ;)

**Comment by BtoBastian** [comment]
The charts should work now. :)
You should also be able to delete them.
