### ISSUE TITLE
Can not delete old charts.

### ISSUE THREAD

**Issue by montlikadani** [BtoBastian/bStats-Metrics#30]
**When that was resolved, but older charts can not be deleted.**

![kep](https://user-images.githubusercontent.com/30026208/32954823-79a4ab7c-cbb4-11e7-9c4a-469f315e3cdc.png)

**Comment by BtoBastian** [comment]
Hey,
what's the name of your plugin? I have to fix this manually.

**Comment by montlikadani** [comment]
@BtoBastian 
TabList: https://bstats.org/plugin/bukkit/TabList

**Comment by BtoBastian** [comment]
You should be able to delete them now.
