### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by Rocologo** [BtoBastian/bStats-Metrics#34]
Hi BtoBastian

It looks like some data is missing in the reports. I have two plugins:
https://bstats.org/plugin/bukkit/BagOfGold
https://bstats.org/plugin/bukkit/MobHunting

Both plugins is installed on my server mc.lindegaard.one which is located in Denmark, but when I looks at your graphs (server map)
![billede](https://user-images.githubusercontent.com/1008133/36023820-0b8b46f2-0d8e-11e8-8a4c-50593422d6fa.png)

Denmark is not on the map???

**Comment by BtoBastian** [comment]
It has been quite a while since I've updated the GeoIP database.
I'll update it when I have time. :-)
Afterwards the map should be more accurate.

**Comment by Rocologo** [comment]
I dont think this is the problem, Denmark and my server was on the map in the past. So something must have changed.

**Comment by sgdc3** [comment]
@BtoBastian you should add an auto doenload task every x days

**Comment by BtoBastian** [comment]
Hey, I've updated the GeoIP database yesterday.
Did this solve the issue?

**Comment by Rocologo** [comment]
Im not sure if your Geo database is the problem. Denmark must have been the database all the time. I have had a server running 24/7/365 all the time and i have sern Denmark on the map almost everytime i checked the stats. 

I have a test server running on the same ip addres (when i develop) which also send statistics to bStats. My my ip address was kund of blacklisted?

**Comment by BtoBastian** [comment]
There's an ip and and uuid ratelimit.
It's unlikely that you hit the ip ratelimit, so maybe you copied the bStats folder and hit the uuid ratelimit.
However, even in this case the country should still be visible (it would just display the data from your testserver instead of your main server).

Are you sure the denmark server was your own and not someone else using your plugin? Maybe the map was wrong the whole time and you just didn't notice.

**Comment by Rocologo** [comment]
I did not copy the folder, so the uuid is different. But i start and stop the testserver alot.

I cant tell if there is other danish servers which uses my two plugins, but I dont think so. But I have no ways to detect if it is mine I see on the map. 

My public ip is dynamic, but it only changes 1 or 2 times a month. Could this be a problem? When my ip changes i do of cause update my dns server, so mc.lindegaard.one is my current ip address.

**Comment by Rocologo** [comment]
I did not copy the folder, so the uuid is different. But i start and stop the testserver alot.

I cant tell if there is other danish servers which uses my two plugins, but I dont think so. But I have no ways to detect if it is mine I see on the map. 

My public ip is dynamic, but it only changes 1 or 2 times a month. Could this be a problem? When my ip changes i do of cause update my dns server, so mc.lindegaard.one is my current ip address.

**Comment by BtoBastian** [comment]
The location of the server is based on the server's ip.
If your ip changes a lot, that's most likely the reason.

**Comment by Rocologo** [comment]
Ahh, so when my ip address changes the geo database must be updated before it is show on the map. 

I think this is the problem. I would be nice if you could update the geo database automatically every night? (If possible).

**Comment by BtoBastian** [comment]
```
Ahh, so when my ip address changes the geo database must be updated before it is show on the map
```
No, your server will always be displayed on the map, but the location might be wrong. Afaik this should only happen, if ip addresses get sold to a new hoster in a different country (e.g. a German hoster get's ip addresses from a French hoster). This shouldn't happen very often, so daily updates aren't really necessary (the free version of the database only receives updates once per month anyway).
