### ISSUE TITLE
Multiple plugins using bStats-Metrics

### ISSUE THREAD

**Issue by dirtyequi** [BtoBastian/bStats-Metrics#4]
We've discovered a strange behaviour when mutiple plugins use bStats-Metrics: Only one/the first loaded (?) plugin is sending it's metrics, others don't. So other plugins won't update on the metrics website (see https://bstats.org/plugin/bukkit/Bedrock for example).

Can you please fix that, so that all plugins will report their existence/data?

**Comment by BtoBastian** [comment]
The first loaded plugin sends the data of the other plugins, too.
It's only one request, but it contains the data of the other plugins as well.

**Comment by dirtyequi** [comment]
Indeed. Here's some debug output I've added just before sending this data:

`{"onlineMode":0,"bukkitVersion":"1.11.2","serverUUID":"2318866d-9602-4c74-87fb-350ebaebe2e2","osVersion":"3.16.0-4-amd64","playerAmount":1,"javaVersion":"1.8.0_73","plugins":[{"pluginVersion":"2.1-SNAPSHOT","pluginName":"UUIDHamster","customCharts":[]},{"pluginVersion":"2.7.1","pluginName":"PlaceholderAPI","customCharts":[{"chartId":"using_expansion_cloud","data":{"value":"yes"}},{"chartId":"using_spigot","data":{"value":"yes"}}]}],"osArch":"amd64","osName":"Linux","coreCount":8}
`

On the server there are four self-written plugins (Bedrock, UUIDHamster, CNShop, Emerald Bank) that use bStats-Metrics:

`>pl
[22:41:05 INFO]: Plugins (37): dynmap, WorldEdit, Rocket, PlaceholderAPI, NBTEditor, PlugMan, Modifyworld, WorldBorder, Yamler, YASPawn, Multiverse-Core, WorldGuard, ProtocolLib, NoCheatPlus, ItemTagger, PluginList, Bedrock, PermissionsEx, geSuitTeleports, WGCustomFlags, geSuiteSpawn, Vault, EntityRemoverPlugin, Prism, VentureChat, UUIDHamster, Essentials, geSuitPortals, geSuitWarps, BlockHat, LWC, Citizens, Shopkeepers, VanishNoPacket, EmeraldBank, BungeeTabListPlus, CNShop
`

So plugins are missing.

**Comment by BtoBastian** [comment]
Did you modify the interval (especially the initial 5 minutes delay) in which the plugin sends it's data?

**Comment by dirtyequi** [comment]
Nope. If you looked this up in your log - I'm currently in heavy development, so server restarts are very often.

**Comment by Blacksheep92** [comment]
Same here.

It looks like this code does not work as intended.
`        for (Class<?> service : Bukkit.getServicesManager().getKnownServices()) {
            try {
                service.getField("B_STATS_VERSION"); // Our identifier :)
            } catch (NoSuchFieldException ignored) {
                continue; // Continue "searching"
            }
            // Found one!
            try {
                pluginData.add(service.getMethod("getPluginData").invoke(Bukkit.getServicesManager().load(service)));
            } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException ignored) {
            }
        }`

If I replace the code above with this:
`        for (RegisteredServiceProvider<MetricsLite> serviceProvider : Bukkit.getServicesManager().getRegistrations(MetricsLite.class)) {
            pluginData.add(serviceProvider.getProvider().getPluginData());
        }`
It collects the data of all plugins.

Yes, this would only track Spigot plugins using MetricsLite. So also not optimal.

**Comment by Blacksheep92** [comment]
I've looked more closely,

The Bukkit Service register call will just register the first for a specific class in the providers map.
getKnownServices is returning the keyset of this providers map.
(Source: [https://gitlab.prok.pw/Mirrors/Bukkit/commit/25faa992ec91f618ee305581c34d044f9eb6beeb?view=parallel&w=1#238f533ecedc32780ff089eb6887d5e081d5ed99_0_34](url))

In our case, we are using an API Plugin, to prevent adding the same code in each plugin again & again.

Thus, the package of MetricsLite.class is identical for all plugins that build on this API.
-> getKnownServices knows only the 1st plugin, which uses this API.

Do you have an idea how to get rid of this problem?
I think over time, more developers will run into this problem.

**Comment by Blacksheep92** [comment]
Fixed :) 
https://github.com/BtoBastian/bStats-Metrics/pull/6

**Comment by BtoBastian** [comment]
Great, thank you! :)
I'll have to take a closer look at the bug, but your explanation makes sense.
