### ISSUE TITLE
Bukkit Services vs. plugins

### ISSUE THREAD

**Issue by dirtyequi** [BtoBastian/bStats-Metrics#5]
The submitted metrics do only contain information about plugins that have registered a service to the Bukkit ServiceManager (like Placeholder API). In addition, not all plugins that registered services are in the submitted plugin data - only the first plugin that has been loaded. I guess this is related to https://github.com/BtoBastian/bStats-Metrics/issues/4

**Comment by BtoBastian** [comment]
See https://github.com/BtoBastian/bStats-Metrics/issues/4#issuecomment-289240310

**Comment by dirtyequi** [comment]
can be closed, as the underlying problem is the same as described in #4
