### ISSUE TITLE
Packages names correct but still getting an error

### ISSUE THREAD

**Issue by ClickPT** [BtoBastian/bStats-Metrics#7]
I am getting this error: ¨bStats Metrics class has not been relocated correctly!¨, but I think that I am using the correct package names.
![screenshot_1](https://cloud.githubusercontent.com/assets/12418685/24589917/c0dcf5c8-17da-11e7-82aa-d931538d5a4d.png)

**Comment by Scarsz** [comment]
You need to move it from the `org.bstats` package to your own.
