### ISSUE TITLE
Don't hard-fail if not relocated. Allow a way of keeping it running for when the plugin is run from IDE.

### ISSUE THREAD

**Issue by me4502** [BtoBastian/bStats-Metrics#8]
I'm using Gradle shade to shade bStats and relocate. This works great for releases, but when running from an IDE it fails. This is because relocating is done at shade-time, and the IDE does not run the shade task.

Some solutions are:

* System property to ignore the check
* Check for IDE runtimes (IntelliJ/Eclipse)
* Only output a massive warning into the console rather than hard fail.

Overall I'd prefer the last solution, but the first is workable.

**Comment by BtoBastian** [comment]
Hmm, that's something I did not have in mind when creating the check.
I prefer the first solution. With the last solution developers may overlook the warning and then the users of the plugin have it in their console which isn't relevant for them.

**Comment by me4502** [comment]
Fair enough, if I have some time tomorrow I can probably PR it in

**Comment by BtoBastian** [comment]
Hey,
are you still planning on making a PR?
Otherwise I would implement it myself.

**Comment by me4502** [comment]
Don't currently have time sorry
